name: Scrape FIIs -> Google Sheets

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *' # roda todo dia às 12:00 UTC (ajuste se quiser)

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci || npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run scraper
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          SHEET_TAB: ${{ secrets.SHEET_TAB }}
          PLAYWRIGHT_STORAGE: ${{ secrets.PLAYWRIGHT_STORAGE }}
        run: node index.js
