name: Run StatusInvest Scraper

on:
  schedule:
    - cron: '0 12 * * *'  # Executa todo dia ao meio-dia
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Upload CSV
        uses: actions/upload-artifact@v3
        with:
          name: fiis-data
          path: fiis_statusinvest.csv
